
SET(CMAKE_SYSTEM_NAME Windows)

# specify the cross compiler
SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-c++)
SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32/sys-root/mingw)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(QT_QMAKE_EXECUTABLE /usr/x86_64-w64-mingw32/bin/qmake-qt5 CACHE INTERNAL "" FORCE)
SET(QT_MOC_EXECUTABLE /usr/x86_64-w64-mingw32/bin/moc-qt5 CACHE INTERNAL "" FORCE)
SET(QT_RCC_EXECUTABLE /usr/x86_64-w64-mingw32/bin/rcc-qt5 CACHE INTERNAL "" FORCE)
SET(QT_UIC_EXECUTABLE /usr/x86_64-w64-mingw32/bin/uic-qt5 CACHE INTERNAL "" FORCE)
